[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "NN"
version = "v1.0"
requires-python = ">= 3.9"

[project.gui-scripts]
test = "test:main_test"

[tool.black]