# Copyright, Damian Andrysiak 2024 XXI. century

_target_: "Dataset.DatasetUE"
datasetRootPath: R"F:\MASTERS\UE4\DATASET\Rainforest_Scene_4_26_2"
csvPath: R"F:\MASTERS\UE4\DATASET\Rainforest_Scene_4_26_2\DumpedBuffers\info_TAA.csv"