# Copyright, Damian Andrysiak 2024 XXI. century

#Main config, used for specifying rest of configuration file tree

defaults:
    - dataset: UE
    # - model: Default_Description
    - loss: MSE
    # - optimizer: Default_Description
  
# dataset: UE
# - model: Default_Description
# - loss: Default_Description
# - optimizer: Default_Description