# Copyright, Damian Andrysiak 2024 XXI. century

#Main config, used for specifying rest of configuration file tree

defaults:
    - Defaults/a: Default_Description
    - b: Default_Description
    - c: Default_Description