# Copyright, Damian Andrysiak 2024 XXI. century

_target_: torch.utils.data.dataloader.DataLoader
dataset: !!null
batch_size: ${..hyperparams.batchSize}
shuffle: True
num_workers: 1
pin_memory: False
drop_last: True