# Copyright, Damian Andrysiak 2024 XXI. century

_target_: NN.NeuralNetworkArchitecture.ModelKPN
name: "ModelKPN_v1"
modelInputs:
    #inputShape: (1, 3, 1920, 1080)  # NCHW
    #outputShape: (1, 3, 1920, 1080)  # NCHW
